# Generated by Django 4.2.7 on 2026-05-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0004_alter_emploidutemps_options_alter_etudiant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('nb_absences', models.PositiveIntegerField(default=0)),
                ('absences_non_justifiees', models.PositiveIntegerField(default=0)),
                ('lue', models.BooleanField(default=False)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='portail.etudiant')),
            ],
            options={
                'ordering': ['-creee_le'],
            },
        ),
    ]
